web:
 image: nginx:latest
 ports:
 - "8080:80"
 volumes:
 - ./site:/site
 - ./health:/site/health
 - ./site.conf:/etc/nginx/conf.d/default.conf
 links:
 - php
php:
 image: php:7-fpm
 volumes:
        - ./site:/site
        - ./health:/site/health
