replicaCount: 1
image:
  repository: <replace_ecr>
  tag: 0.1.0
  pullPolicy: Always
nginxService:
  name: nginx
  type: LoadBalancer
  externalPort: 80
  internalPort: 80
phpfpmService:
  name: php
  type: NodePort
  phpfpmPort: 9000
config:
  nginx.conf: |-
    server {
      listen 0.0.0.0:8080;
      root /app;
      location / {
        index index.html index.php;
      }
      location ~ \.php$ {
        fastcgi_pass phpfpm-php-app-phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
